//GET ohne zusätzliche Information -> alle GeoTags zurückgeben
GET http://localhost:3000/api/geotags
Accept: application/json
###

//POST einen GeoTag posten bla
POST http://localhost:3000/api/geotags
Content-Type: application/json

{
  "name":"bla",  
  "latitude":"49.013790",
  "longitude":"8.404435",
  "hashtag":"#bla"
}
###

//GET einzelner GeoTag bla
GET http://localhost:3000/api/geotags/bla
Accept: application/json
###


###
//PUT Ändere bla zu blub
PUT http://localhost:3000/api/geotags/bla
Content-Type: application/json

{
  "name":"blub",
  "latitude":"49.013790",
  "longitude":"8.404435",
  "hashtag":"#blub"
}
###

//DELETE blub 
DELETE http://localhost:3000/api/geotags/blub
###

//GET nur nach searchterm gefiltert
GET http://localhost:3000/api/geotags?searchterm=campus
###

//GET nur nach standort gefiltert
GET http://localhost:3000/api/geotags?latitude=49.00902&longitude=8.39772
###

//GET nach searchterm & standort gefiltert
GET http://localhost:3000/api/geotags?searchterm=campus&latitude=49.00902&longitude=8.39772
###

GET http://localhost:3000/api/geotags/page/1
Content-Type: application/json

[{"name":"Castle","location":{"latitude":49.01379,"longitude":8.404435},"hashtag":"#sight"},
  {"name":"IWI","location":{"latitude":49.01379,"longitude":8.390071},"hashtag":"#edu"},
  {"name":"Building E","location":{"latitude":49.014993,"longitude":8.390049},"hashtag":"#campus"},
  {"name":"Building F","location":{"latitude":49.015608,"longitude":8.390112},"hashtag":"#campus"},
  {"name":"Building M","location":{"latitude":49.016171,"longitude":8.390155},"hashtag":"#campus"},
  {"name":"Building LI","location":{"latitude":49.015636,"longitude":8.389318},"hashtag":"#campus"},
  {"name":"Auditorium He","location":{"latitude":49.014915,"longitude":8.389264},"hashtag":"#campus"},
  {"name":"Building R","location":{"latitude":49.014992,"longitude":8.392365},"hashtag":"#campus"},
  {"name":"Building A","location":{"latitude":49.015738,"longitude":8.391619},"hashtag":"#campus"},
  {"name":"Building B","location":{"latitude":49.016843,"longitude":8.391372},"hashtag":"#campus"},
  {"name":"Building K","location":{"latitude":49.01319,"longitude":8.39209},"hashtag":"#campus"}]
###

//GET nach searchterm & standort gefiltert
GET http://localhost:3000/api/geotags?searchterm=campus&latitude=49.00902&longitude=8.39772&offset=2&limit=3
###